### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by gpsathas** [ibleducation/jupyter-viewer-xblock#1]
I tried to follow the instructions from the readme file, but I am receiving an error saying:
 
WE'RE HAVING TROUBLE RENDERING YOUR COMPONENT
Students will not be able to access this component. Re-edit your component to fix the error.
**Error: Reverse for 'jupyter_nb_viewer' not found. 'jupyter_nb_viewer' is not a valid view function or pattern name.**

I tried to install the Xblock on both Gingko.2 and Hawthorn.beta1 releases with the same negative results.

**Comment by mamigot** [comment]
Hey @gpsathas,

Were you able to follow the “LMS/CMS Setup” instructions in the README as well?

The XBlock relies on a couple of API endpoints, which is why this is necessary.

Please let us know, and thanks!

**Comment by gpsathas** [comment]
Fortunately, I managed to install XBlock, but I used your AMI in Community AMIs.

Still, I didn't realize what the problem with my installation was! Missing some prerequisites maybe? If you have some advice for me to follow please tell me because I want to use my own instance.

**Comment by mamigot** [comment]
Great to hear that the OpenIBL AMI (Ginkgo.2) installation helped you!

The fact that it's not possible for you to install this XBlock on your own installation might have to do with the stability of your Open edX instance as opposed to the XBlock's, unfortunately. We've tested the XBlock thoroughly across multiple versions of Open edX and it seems like you've followed all the right instructions!

If you have `cms` or `lms` logs — depending on where you saw this error — it may be possible to identify the problem with your installation of Open edX, but that has a pretty wide surface area.

Closing this issue but feel free to reopen it if you encounter any problem, @gpsathas !

**Comment by moocitfrance** [comment]
Hi, we have the exact same issue on Hawhtorn. 
Are you sure there is no missing steps in the installation ? 

`File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/xblock/runtime.py", line 810, in render
    frag = view_fn(context)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/xblock_jupyter_viewer/xblock_jupyter_viewer.py", line 69, in student_view
    base = reverse('jupyter_nb_viewer') + "?{}"
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
NoReverseMatch: Reverse for 'jupyter_nb_viewer' not found. 'jupyter_nb_viewer' is not a valid view function or pattern name.`

**Comment by jganzabal** [comment]
exact same problem here with Hawhtorn

**Comment by geoff-va** [comment]
This has been [fixed](https://github.com/ibleducation/jupyter-viewer-xblock/commit/42f2e41d9d0c2069c5c3f5334d57048ee4c757ca).

Feel free to re-open if you still have the same problem.
